language: node_js
node_js: 13.5.0

os:
  - linux
  - osx
  - windows

dist: trusty

notifications:
  email: false

addons:
  apt:
    packages:
      - rpm

jobs:
  include:
    - os: linux
      stage: Publish
      script:
        - npm run release
    - os: osx
      stage: Publish
      script:
        - du -c -h -d1 ~/
        - ls ~/.cache
        - npm run release -- --mac
    - os: windows
      stage: Publish
      script:
        - npm run release -- --win

install:
  - npm install

script:
  - npm run compile