language: node_js

os:
  - linux
  - osx
  - windows

dist: trusty

notifications:
  email: false

addons:
  apt:
    packages:
      - rpm

jobs:
  include:
    - os: linux
      stage: Publish
      script:
       - npm run release
    - os: osx
      stage: Publish
      script:
       - npm run release -- --mac
    - os: windows
      stage: Publish
      script:
       - npm run release -- --win

install:
  - npm install

script:
  - npm run compile