language: node_js
node_js: 13.5.0

os:
  - linux
  - osx
  - windows

dist: trusty

notifications:
  email: false

addons:
  apt:
    packages:
      - rpm

jobs:
  include:
    - stage: Publish
      install:
        - npm install
        - npm run compile
      - os: linux
        script:
          - npm run release
      - os: osx
        script:
          - npm run release -- --mac
      - os: windows
          script:
          - npm run release -- --win

install:
  - npm install

script:
  - npm run compile